---

- name: create base directories to save builds
  file: path=/builds/ state=directory  owner=jenkins group=jenkins

- name: create base directories to save esxi builds
  file: path=/builds/esxi/ state=directory  owner=jenkins group=jenkins

- name: create dir for esxi 5.5 u3
  file: path=/builds/esxi/3029944/ state=directory  owner=jenkins group=jenkins

- name: copy extract_iso.sh
  copy: src=extract_iso.sh dest=/builds/esxi/ owner=jenkins group=jenkins mode=0755

- name: copy esxi 5.5 u3 build
  copy: src=ubuntu-14.04.1-server-amd64.iso dest=/builds/esxi/3029944/ force=no owner=jenkins group=jenkins mode=0644

- command: /builds/esxi/extract_iso.sh ubuntu-14.04.1-server-amd64.iso
  args:
    chdir: /builds/esxi/3029944/
    creates: build.ready