---

# Use following command to trigger this yaml
# ansible-playbook sites.yml -i hosts -u [SSH_USER]

- include: atp_install.yml

- include: jenkins.yml

- include: esx_builds.yml

- include: apache2.yml
