---

# Use following command to trigger this yaml
# ansible-playbook sites.yml -i hosts -u vagrant

- include: atp_install.yml

- name: setting tftp config file permissions
  file: path=/etc/default/tftpd-hpa owner=jenkins group=jenkins

- include: jenkins.yml
